CREATE SEQUENCE POINTSEQ NOCACHE;

CREATE TABLE POINT(
	POINTSEQ NUMBER PRIMARY KEY,
	POINTID VARCHAR2(50) NOT NULL,			-- 유저 아이디
	POINTDETAIL VARCHAR2(1000) NOT NULL,	-- 포인트 내역
	POINTGETDATE DATE NOT NULL,				-- 포인트 획득일
	GETPOINT NUMBER NOT NULL,				-- 획득 포인트
	USEPOINT NUMBER NOT NULL,				-- 사용 포인트
	TOTALPOINT NUMBER NOT NULL,				-- 총 포인트
	POINTIMG VARCHAR2(2000) NOT NULL,		-- 포인트 이미지
	CONSTRAINT FK_ID_POINT FOREIGN KEY(POINTID) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE
);

SELECT * FROM POINT;

DROP TABLE POINT;