CREATE SEQUENCE POINTSEQ NOCACHE;

CREATE TABLE POINT(
	POINTSEQ NUMBER PRIMARY KEY,
	POINTID VARCHAR2(50) NOT NULL,			-- 유저 아이디
	POINTDETAIL VARCHAR2(1000) DEFAULT '룰렛 이벤트' NOT NULL,	-- 포인트 내역
	POINTGETDATE VARCHAR2(100) NOT NULL,				-- 포인트 획득일
	GETPOINT NUMBER NOT NULL,				-- 획득 포인트
	USEPOINT NUMBER DEFAULT 0 NOT NULL,				-- 사용 포인트
--	TOTALPOINT NUMBER NOT NULL,				-- 총 포인트
	CONSTRAINT FK_ID_POINT FOREIGN KEY(POINTID) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE
);

INSERT INTO POINT(POINTSEQ, POINTID, POINTDETAIL, POINTGETDATE, GETPOINT, USEPOINT)
VALUES(POINTSEQ.NEXTVAL, 'USER4', '룰렛 이벤트', SYSDATE, 1000, 0);

INSERT INTO POINT(POINTSEQ, POINTID, POINTDETAIL, POINTGETDATE, GETPOINT, USEPOINT)
VALUES(POINTSEQ.NEXTVAL, 'admin', '룰렛 이벤트', SYSDATE, 2000, 0);

SELECT * FROM POINT;

DROP TABLE POINT;
DROP SEQUENCE POINTSEQ;