select * from user_tables;

CREATE SEQUENCE JOONGGOSEQ NOCACHE;
CREATE SEQUENCE HITSEQ NOCACHE;
CREATE SEQUENCE RENEWSEQ NOCACHE;
CREATE SEQUENCE REPORTSEQ NOCACHE;
CREATE SEQUENCE REPORTANSWERSEQ NOCACHE;

CREATE TABLE MYMEMBER(
    MYNO NUMBER NOT NULL,
    MYID VARCHAR2(500) NOT NULL,
    MYPW VARCHAR2(500) NOT NULL,
    MYNAME VARCHAR2(1000) NOT NULL,
    MYADDR VARCHAR2(4000) NOT NULL,
    MYPHONE VARCHAR2(20) NOT NULL,
    MYEMAIL VARCHAR2(100) NOT NULL,
    MYBIRTH DATE NOT NULL,
    MYSEX VARCHAR2(10) NOT NULL,
    MYENABLED VARCHAR2(2) NOT NULL,
    MYROLE VARCHAR2(50) NOT NULL,
    MYPENALTY NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT MYMEMBER_PK PRIMARY KEY(MYNO),
    CONSTRAINT MYMEMBER_UQ_ID UNIQUE(MYID),
    CONSTRAINT MYMEMBER_UQ_PHONE UNIQUE(MYPHONE),
    CONSTRAINT MYMEMBER_UQ_EMAIL UNIQUE(MYEMAIL),
    CONSTRAINT MYMEMBER_SEX_CHK CHECK( MYSEX IN('남성','여성')),
    CONSTRAINT MYMEMBER_ENABLED_CHK CHECK( MYENABLED IN('Y','N'))
);

--1)
CREATE TABLE JOONGGO(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	REGDATE DATE NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT CLOB NOT NULL,
	CATEGORY VARCHAR2(100) NOT NULL,
	PRICE NUMBER NOT NULL,
	PLACE VARCHAR2(100) NULL,
	TAG VARCHAR2(100) NOT NULL,
	QUALITY VARCHAR2(20) NOT NULL,
	DELIVERY VARCHAR2(20) NOT NULL,
	AGREE VARCHAR2(20) NOT NULL,
	TRADE VARCHAR2(20) DEFAULT 'Y' NOT NULL,
	HIT NUMBER DEFAULT 0 NOT NULL,
	HEART NUMBER DEFAULT 0 NOT NULL,
	IMGLIST VARCHAR2(2000) NOT NULL,
	CONSTRAINT FK_ID_JOONGGO FOREIGN KEY(ID) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE,
	CONSTRAINT CK_QUALITY_JOONGGO CHECK (QUALITY IN('A','B','C')),
	CONSTRAINT CK_DELIVERY_JOONGGO CHECK (DELIVERY IN('A','D','C')),
	CONSTRAINT CK_AGREE_JOONGGO CHECK (AGREE IN('Y','N')),
	CONSTRAINT CK_TRADE_JOONGGO CHECK (TRADE IN('Y','N','T'))
);

--2)
CREATE TABLE HITDATA(
	HITSEQ NUMBER PRIMARY KEY,
	HITDATE DATE NOT NULL,
	JOONGGOSEQ NUMBER NOT NULL,
	CONSTRAINT FK_SEQ_HITDATA FOREIGN KEY(JOONGGOSEQ) REFERENCES JOONGGO(SEQ) ON DELETE CASCADE
);

--3) view
CREATE OR REPLACE VIEW HITDATA_VIEW
AS
SELECT K.COUNT, L.* 
FROM (
	SELECT J.JOONGGOSEQ SEQ, COUNT(J.JOONGGOSEQ) COUNT  
	FROM (
		SELECT *
		FROM HITDATA
		WHERE HITDATE >= SYSDATE-7
		) J
	GROUP BY J.JOONGGOSEQ
	) K, JOONGGO L
WHERE 
K.SEQ = L.SEQ
AND L.TRADE = 'Y'
AND L.DELIVERY != 'C'
ORDER BY COUNT DESC

--4) renewal table
CREATE TABLE RENEWAL(
	RENEWSEQ NUMBER PRIMARY KEY,
	RENEWDATE DATE NOT NULL,
	JOONGGOSEQ NUMBER NOT NULL,
	CONSTRAINT FK_SEQ_RENEW FOREIGN KEY(JOONGGOSEQ) REFERENCES JOONGGO(SEQ) ON DELETE CASCADE
)


--5) 찜테이블
CREATE TABLE JOONGGO_HEART(
	HEARTDATE DATE NOT NULL,
	HEARTID VARCHAR2(50) NOT NULL,
	JOONGGOSEQ NUMBER NOT NULL,
	CONSTRAINT FK_SEQ_HEART FOREIGN KEY(JOONGGOSEQ) REFERENCES JOONGGO(SEQ) ON DELETE CASCADE,
	CONSTRAINT FK_ID_HEART FOREIGN KEY(HEARTID) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE,
	CONSTRAINT PK_HEART PRIMARY KEY(HEARTID, JOONGGOSEQ)
)

--6)신고 
CREATE TABLE REPORT(
	REPORTSEQ NUMBER PRIMARY KEY,
	REPORTDATE DATE NOT NULL,
	REPORTID VARCHAR2(50) NULL,
	REPORTCONTENT VARCHAR2(1000) NOT NULL,
	FILEPATH VARCHAR2(1000) NULL,
	JOONGGOSEQ NUMBER NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	STATUS VARCHAR2(20) DEFAULT 'N' NOT NULL,
	CONSTRAINT FK_REPORTID_REPORT FOREIGN KEY(REPORTID) REFERENCES MYMEMBER(MYID) ON DELETE SET NULL,
	CONSTRAINT CK_STATUS_REPORT CHECK (STATUS IN('Y','N'))
)

--7)신고답변
CREATE TABLE REPORT_ANSWER(
	SEQ NUMBER PRIMARY KEY,
	REPORTSEQ NUMBER NOT NULL,
	ADMINID VARCHAR2(50) NOT NULL,
	ADMINTEXT VARCHAR2(1000) NOT NULL,
	CONSTRAINT FK_REPORTSEQ_ANSWER FOREIGN KEY(REPORTSEQ) REFERENCES REPORT(REPORTSEQ) ON DELETE CASCADE
)

--8)chat
CREATE TABLE JOONGGO_CHAT(
	ROOMSEQ NUMBER PRIMARY KEY,
	JOONGGOSEQ NUMBER NOT NULL,
	USERID VARCHAR2(50) NULL,
	WRITER VARCHAR2(50) NULL,
	WRITER_FIX VARCHAR2(50) NOT NULL,
	CREATEDATE DATE NOT NULL,
	CONSTRAINT FK_USERID_CHAT FOREIGN KEY(USERID) REFERENCES MYMEMBER(MYID) ON DELETE SET NULL,
	CONSTRAINT FK_WRITER_CHAT FOREIGN KEY(WRITER) REFERENCES MYMEMBER(MYID) ON DELETE SET NULL
)
CREATE SEQUENCE CHATROOMSEQ NOCACHE;

--9)CHAT DETAIL
CREATE TABLE JOONGGO_CHAT_DETAIL(
	ROOMSEQ NUMBER NOT NULL,
	CHATSEQ NUMBER PRIMARY KEY,
	SENDER VARCHAR2(50) NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	SENDDATE DATE NOT NULL,
	CONSTRAINT FK_ROOMSEQ_DETAIL FOREIGN KEY(ROOMSEQ) REFERENCES JOONGGO_CHAT(ROOMSEQ) ON DELETE CASCADE
)
CREATE SEQUENCE CHATSEQ NOCACHE;

SELECT * FROM JOONGGO_CHAT
SELECT * FROM JOONGGO_CHAT_DETAIL
DELETE FROM JOONGGO_CHAT;
DELETE FROM JOONGGO_CHAT_DETAIL;
DROP SEQUENCE CHATROOMSEQ;
DROP SEQUENCE CHATSEQ;



DROP TABLE JOONGGO;
DROP TABLE HITDATA
DROP TABLE JOONGGO_HEART;
DROP TABLE RENEWAL
DROP TABLE REPORT
DROP TABLE REPORT_ANSWER
SELECT * FROM JOONGGO_HEART
SELECT * FROM JOONGGO
DELETE FROM JOONGGO_HEART
DELETE FROM JOONGGO;
DELETE FROM REPORT;
SELECT * FROM MYMEMBER;
SELECT * FROM RENEWAL;
SELECT * FROM REPORT;

--특정 유저가 삭제가된경우 찜 수 업데이트 필요
--UPDATE JOONGGO
UPDATE JOONGGO J
SET HEART = (SELECT COUNT(*) FROM JOONGGO_HEART H WHERE H.JOONGGOSEQ = J.SEQ ); 

SELECT * 
FROM JOONGGO_CHAT_DETAIL
WHERE SENDDATE < TO_DATE('2022-01-16 01:20:48', 'YYYY-MM-DD HH24:MI:SS')





SELECT *
FROM JOONGGO
WHERE TITLE LIKE '%캠핑용 식기%'
UNION ALL
SELECT *
FROM JOONGGO
WHERE TITLE LIKE '%캠핑용%'

INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, TRADE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '성수역', '의자','B','D','Y','N','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');
INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '경기 성남시 분당구 판교동', '의자','B','D','Y','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');
INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '서울특별시 양천구 목동', '의자','B','D','Y','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');
INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '잠실동,목동', '의자','B','D','Y','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');
INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '잠실동,목동', '의자','B','D','Y','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');
INSERT INTO JOONGGO(SEQ, ID, REGDATE, TITLE, CONTENT, CATEGORY, PRICE, PLACE, TAG, QUALITY, DELIVERY, AGREE, IMGLIST)
VALUES(JOONGGOSEQ.NEXTVAL, 'USER4', SYSDATE, '캠핑용의자랑 기타 물품 팔아요', '팔아용~', '캠핑 > 텐트/타프/매트', 37000, '잠실동,목동', '의자','B','D','Y','https://img.wizwid.com/PImg/706861/bsc/706861593.jpg');

SELECT *
FROM (SELECT ROWNUM AS NUM, J.* FROM (
	  SELECT * FROM JOONGGO 
	  WHERE CATEGORY = '캠핑 > 텐트/타프/매트'  
	  
	  ORDER BY SEQ DESC) J)
WHERE NUM between 7 AND 10;

SELECT J.*
FROM JOONGGO J
WHERE CATEGORY = '캠핑 > 텐트/타프/매트' 
AND ROWNUM BETWEEN 1 AND 10
ORDER BY SEQ DESC;

































