

CREATE SEQUENCE CAMPSEQ NOCACHE;

CREATE TABLE CAMP (
	CAMPNO	NUMBER(10)	CONSTRAINT PK_CAMPNO PRIMARY KEY,
	WRITER	VARCHAR2(500)	NOT NULL,
	NAME	VARCHAR2(300)	NOT NULL,
	CAMP_TYPE	VARCHAR2(500)	NOT NULL,
	ADDRESS	VARCHAR2(200)	NOT NULL,
	ADDRESS_DETAIL	VARCHAR2(200)	NULL,
	SERVICE	VARCHAR2(3000)	NOT NULL,
	INTRO	VARCHAR2(3000)	NOT NULL,
	RULE	VARCHAR2(3000)	NOT NULL,
	PHONE	VARCHAR2(100)	,
	EMAIL	VARCHAR2(100)	,
	TAGS	VARCHAR2(500)	,
	VIEW_COUNT NUMBER(10)	DEFAULT 0,
	TOTAL_GRADE FLOAT DEFAULT 0,
	LOWEST_PRICE VARCHAR2(100),
	THUMBNAIL VARCHAR2(3000) NOT NULL,
	CREATE_DATE	DATE	NOT NULL,
	REVIEW_COUNT NUMBER(10) DEFAULT 0,
	CONSTRAINT FK_WRITER1 FOREIGN KEY (WRITER) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE
);

CREATE SEQUENCE REVIEWSEQ NOCACHE;

CREATE TABLE REVIEW(
	REVIEWNO NUMBER(10) CONSTRAINT PK_REVIEWNO PRIMARY KEY,
	CAMPNO NUMBER(10) NOT NULL,
	WRITER	VARCHAR2(500) NOT NULL,
	TITLE	VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(3000) NOT NULL,
	SERVICE FLOAT NOT NULL,
	CLEANLINESS FLOAT NOT NULL,
	COST	FLOAT NOT NULL,
	LOCATION FLOAT NOT NULL,
	TOTAL	FLOAT NOT NULL,
	THUMBNAIL VARCHAR2(3000) NOT NULL,
	CREATE_DATE DATE	NOT NULL,
	CONSTRAINT FK_CAMPNO1 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE,
	CONSTRAINT FK_WRITER2 FOREIGN KEY (WRITER) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE
);

CREATE SEQUENCE ROOMSEQ NOCACHE;

CREATE TABLE ROOM(
	ROOMNO NUMBER(10) CONSTRAINT PK_ROOMNO PRIMARY KEY,
	CAMPNO NUMBER(10) NOT NULL,
	ROOM_NAME VARCHAR2(300) NOT NULL,
	ROOM_PRICE VARCHAR2(15) NOT NULL,
	GUEST_NUMBER NUMBER(5) NOT NULL,
	ROOM_CONTENT VARCHAR2(3000) NOT NULL,
	THUMBNAIL VARCHAR2(3000) NOT NULL,
	CONSTRAINT FK_CAMPNO2 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE
);

CREATE SEQUENCE RESERVATION_SEQ NOCACHE;

CREATE TABLE RESERVATION(
	RESERVNO NUMBER(10) CONSTRAINT PK_RESERVNO PRIMARY KEY,
	CAMPNO NUMBER(10),
	ROOMNO	NUMBER(10),
	USERID	VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_CONTACT VARCHAR2(500) NOT NULL,
	GUEST_NUMBER NUMBER(5) NOT NULL,
	CHECK_IN DATE NOT NULL,
	CHECK_OUT DATE NOT NULL,
	STATUS VARCHAR2(20) NOT NULL,
	CREATE_DATE DATE NOT NULL,
	CONSTRAINT FK_CAMPNO05 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE,
	CONSTRAINT FK_ROOMNO FOREIGN KEY (ROOMNO) REFERENCES ROOM(ROOMNO) ON DELETE CASCADE,
	CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES MYMEMBER(MYID) ON DELETE CASCADE
);

CREATE SEQUENCE IMAGE_SEQ NOCACHE;

CREATE TABLE CAMP_IMAGE(
	IMAGENO NUMBER(10) CONSTRAINT PK_IMAGENO PRIMARY KEY,
	CAMPNO NUMBER(10) NOT NULL,
	ORG_FILE_NAME VARCHAR2(260) NOT NULL,
	SAVE_FILE_NAME VARCHAR2(40) NOT NULL,
	FILE_SIZE NUMBER(10) NOT NULL,
	DEL_CHK VARCHAR2(2) DEFAULT 'N',
	CONSTRAINT FK_CAMPNO13 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE
);

CREATE SEQUENCE RIMAGE_SEQ NOCACHE;

CREATE TABLE ROOM_IMAGE(
	RIMAGENO NUMBER(10) CONSTRAINT PK_RIMAGENO PRIMARY KEY,
	ROOMNO NUMBER(10) NOT NULL,
	ORG_FILE_NAME VARCHAR2(260) NOT NULL,
	SAVE_FILE_NAME VARCHAR2(40) NOT NULL,
	FILE_SIZE NUMBER(10) NOT NULL,
	DEL_CHK VARCHAR2(2) DEFAULT 'N',
	CONSTRAINT FK_ROOMNO3 FOREIGN KEY (ROOMNO) REFERENCES ROOM(ROOMNO) ON DELETE CASCADE
);

DROP TABLE ROOM_IMAGE;
DROP TABLE CAMP_IMAGE;
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE REVIEW;
DROP TABLE CAMP;

DROP SEQUENCE RIMAGE_SEQ;
DROP SEQUENCE IMAGE_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE ROOMSEQ;
DROP SEQUENCE REVIEWSEQ;
DROP SEQUENCE CAMPSEQ;

SELECT * FROM MYMEMBER;
SELECT * FROM ROOM_IMAGE;
SELECT * FROM ROOM;
SELECT * FROM CAMP_IMAGE;
SELECT * FROM CAMP;
SELECT * FROM REVIEW;
SELECT * FROM RESERVATION;

UPDATE CAMP SET THUMBNAIL=(CAMPSEQ.CURRVAL) WHERE CAMPNO=1;
select campseq.currval from dual;
select campno from(   select *   from camp order by campno DESC)where ROWNUM = 1;
UPDATE CAMP    SET THUMBNAIL='test' WHERE CAMPNO=(select campno from(select * from camp order by campno DESC)where ROWNUM = 1);
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실1','30000','4','배경이 아주 좋음');
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실2','45000','4','배경이 아주 좋음');
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실3','50000','6','배경이 아주 좋음');
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실4','60000','6','배경이 아주 좋음');
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실5','70000','8','배경이 아주 좋음');
INSERT INTO ROOM VALUES (ROOMSEQ.NEXTVAL,1,'객실6','80000','8','배경이 아주 좋음');

INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL,8,'ADMIN1','홍길동','111-111-1111',3,'2022-01-11','2022-01-13','Y',SYSDATE);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL,8,'ADMIN1','홍길동','111-111-1111',3,'2022-01-23','2022-01-27','Y',SYSDATE);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL,9,'ADMIN1','홍길동','111-111-1111',3,TO_DATE('2022-01-11','YYYY-MM-DD'),TO_DATE('2022-01-13','YYYY-MM-DD'),'Y',SYSDATE);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL,9,'ADMIN1','홍길동','111-111-1111',3,TO_DATE('2022-01-23','YYYY-MM-DD'),TO_DATE('2022-01-27','YYYY-MM-DD'),'Y',SYSDATE);
SELECT * FROM RESERVATION WHERE ROOMNO=9;
SELECT * FROM (SELECT ROOM_PRICE FROM ROOM ORDER BY CAMPNO,CAST(ROOM_PRICE AS NUMBER)) WHERE ROWNUM=1;
SELECT CAMPNO FROM CAMP ORDER BY CAMPNO DESC;
ALTER TABLE CAMP MODIFY TOTAL_GRADE FLOAT;
UPDATE CAMP SET TOTAL_GRADE=(SELECT ROUND(AVG(TOTAL),1) FROM REVIEW WHERE CAMPNO=1) WHERE CAMPNO=1;

SELECT CAMPNO FROM CAMP WHERE ROWNUM=1 ORDER BY CAMPNO DESC;

ALTER TABLE CAMP ADD REVIEW_COUNT NUMBER(10) DEFAULT 0;

UPDATE CAMP SET REVIEW_COUNT=(SELECT COUNT(*) FROM REVIEW WHERE CAMPNO=1) WHERE CAMPNO=1;

SELECT * FROM CAMP WHERE ROWNUM<5 ORDER BY REVIEW_COUNT DESC;
SELECT * FROM CAMP WHERE ROWNUM<3 ORDER BY CAMPNO DESC;