

CREATE SEQUENCE CAMPSEQ NOCACHE;

CREATE TABLE CAMP (
	CAMPNO	NUMBER(10)	CONSTRAINT PK_CAMPNO PRIMARY KEY,
	WRITER	VARCHAR2(500)	NOT NULL,
	NAME	VARCHAR2(200)	NOT NULL,
	CAMP_TYPE	VARCHAR2(50)	NOT NULL,
	ADDRESS	VARCHAR2(200)	NOT NULL,
	ADDRESS_DETAIL	VARCHAR2(200)	NULL,
	SERVICE	VARCHAR2(3000)	NOT NULL,
	INTRO	VARCHAR2(3000)	NOT NULL,
	RULE	VARCHAR2(3000)	NOT NULL,
	PHONE	VARCHAR2(100)	,
	EMAIL	VARCHAR2(100)	,
	TAG		VARCHAR2(100)	,
	VIEW_COUNT NUMBER(10)	NOT NULL,
	CREATE_DATE	DATE	NOT NULL,
	CONSTRAINT FK_WRITER1 FOREIGN KEY (WRITER) REFERENCES MYMEMBER(USERID) ON DELETE CASCADE
);

CREATE SEQUENCE REVIEWSEQ NOCACHE;

CREATE TABLE REVIEW(
	REVIEWNO NUMBER(10) CONSTRAINT PK_REVIEWNO PRIMARY KEY,
	CAMPNO NUMBER(10) NOT NULL,
	WRITER	VARCHAR2(500) NOT NULL,
	TITLE	VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(3000) NOT NULL,
	SERVICE NUMBER(10) NOT NULL,
	CLEANLINESS NUMBER(10) NOT NULL,
	COST	NUMBER(10) NOT NULL,
	LOCATION NUMBER(10) NOT NULL,
	TOTAL	NUMBER(10) NOT NULL,
	CREATE_DATE DATE	NOT NULL,
	CONSTRAINT FK_CAMPNO1 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE,
	CONSTRAINT FK_WRITER2 FOREIGN KEY (WRITER) REFERENCES MYMEMBER(USERID) ON DELETE CASCADE
);

CREATE SEQUENCE ROOMSEQ NOCACHE;

CREATE TABLE ROOM(
	ROOMNO NUMBER(10) CONSTRAINT PK_ROOMNO PRIMARY KEY,
	CAMPNO NUMBER(10) NOT NULL,
	PRICE VARCHAR2(15) NOT NULL,
	GUEST_NUMBER NUMBER(5) NOT NULL,
	ENABLED VARCHAR2	NOT NULL,
	CHECK_IN	DATE NOT NULL,
	CHECK_OUT	DATE NOT NULL,
	CONSTRAINT CHK_ENABLED CHECK(ENABLED IN('Y','N')),
	CONSTRAINT FK_CAMPNO2 FOREIGN KEY (CAMPNO) REFERENCES CAMP(CAMPNO) ON DELETE CASCADE
);

CREATE SEQUENCE RESERVATION_SEQ NOCACHE;

CREATE TABLE RESERVATION(
	RESERVNO NUMBER(10) CONSTRAINT PK_RESERVNO PRIMARY KEY,
	ROOMNO	NUMBER(10) REFERENCES ROOMNO (ROOM),
	USERID	VARCHAR2(500) NOT NULL,
	GUEST_NUMBER NUMBER(5) NOT NULL
	CONSTRAINT FK_ROOMNO FOREIGN KEY (ROOMNO) REFERENCES ROOM(ROOMNO) ON DELETE CASCADE,
	CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES MYMEMBER(USERID) ON DELETE CASCADE
);
